name: Build RustDesk Client (custom server, vcpkg manifest via setup-vcpkg, MSVC)

on:
  workflow_dispatch:

jobs:
  build-win-msvc:
    runs-on: windows-latest
    env:
      # Задай в Settings → Actions → Variables:
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}   # напр.: hbbs.example.com:21115
      RS_PUB_KEY:        ${{ vars.RS_PUB_KEY }}          # ssh-ed25519 AAAA... (одной строкой)
      RELAY_SERVER:      ${{ vars.RELAY_SERVER }}        # опц.: hbbr.example.com:21117
      RUST_BACKTRACE: "1"
      CARGO_TERM_COLOR: always
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - name: Checkout this CI repo
        uses: actions/checkout@v4

      - name: Cleanup previous run
        shell: cmd
        run: |
          if exist rustdesk rmdir /s /q rustdesk

      # Клонируем ИМЕННО клиент rustdesk и инициализируем сабмодули из корня
      - name: Clone RustDesk (client) + submodules
        shell: cmd
        run: |
          git config --global core.longpaths true
          git clone https://github.com/rustdesk/rustdesk.git rustdesk
          git -C rustdesk submodule sync --recursive
          git -C rustdesk submodule update --init --recursive

      # Rust (MSVC)
      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      # Flutter (GUI)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        shell: pwsh
        run: flutter doctor -v

      # Инструменты C/C++ (через cmd, без refreshenv)
      - name: Install build tools (cmd)
        shell: cmd
        run: |
          choco install cmake ninja -y --no-progress
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart" -y --no-progress
          cmake --version
          ninja --version

      # === vcpkg через официальный экшен (ставит VCPKG_ROOT и кеширует) ===
      # Ставим зависимости из rustdesk/vcpkg.json для СТАТИЧЕСКОГО триплета
      - name: setup-vcpkg (x64-windows-static)
        uses: microsoft/setup-vcpkg@v1
        with:
          # куда положить vcpkg (стабильный путь, кэшируется)
          vcpkgDirectory: ${{ runner.temp }}\vcpkg
          # каталог с vcpkg.json (manifest mode)
          workingDirectory: rustdesk
          # нужный триплет
          triplet: x64-windows-static
          # к ключу кеша добавим метку, чтобы не путать с динамикой
          appendedCacheKey: rustdesk-static

      # И ставим зависимости для ДИНАМИЧЕСКОГО триплета (fallback)
      - name: setup-vcpkg (x64-windows)
        uses: microsoft/setup-vcpkg@v1
        with:
          vcpkgDirectory: ${{ runner.temp }}\vcpkg
          workingDirectory: rustdesk
          triplet: x64-windows
          appendedCacheKey: rustdesk-dynamic

      # Печать кастомных переменных (проверка)
      - name: Print custom vars
        shell: pwsh
        run: |
          echo "RENDEZVOUS_SERVER=$env:RENDEZVOUS_SERVER"
          if ($env:RELAY_SERVER) { echo "RELAY_SERVER=$env:RELAY_SERVER" }
          echo "RS_PUB_KEY length: $($env:RS_PUB_KEY.Length)"
          echo "VCPKG_ROOT (from setup-vcpkg) = $env:VCPKG_ROOT"

      # Сборка В ОДНОМ cmd-шаге:
      # 1) VsDevCmd (MSVC/SDK);
      # 2) авто-выбор статик/динамик по наличию opus_multistream.h в $VCPKG_ROOT\installed\<triplet>\include\opus;
      # 3) сборка rustdesk.exe
      - name: Build RustDesk (release, MSVC) with vcpkg (auto static→dynamic)
        shell: cmd
        working-directory: rustdesk
        env:
          RENDEZVOUS_SERVER: ${{ env.RENDEZVOUS_SERVER }}
          RELAY_SERVER:      ${{ env.RELAY_SERVER }}
          RS_PUB_KEY:        ${{ env.RS_PUB_KEY }}
        run: |
          rem 1) Активируем MSVC/SDK
          if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          ) else (
            call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=x64
          )

          rem 2) setup-vcpkg уже выставил VCPKG_ROOT и поставил пакеты для двух триплетов
          set STATIC_TRIPLET=x64-windows-static
          set DYNAMIC_TRIPLET=x64-windows

          rem 3) Автоматический выбор по наличию заголовков Opus:
          if exist "%VCPKG_ROOT%\installed\%STATIC_TRIPLET%\include\opus\opus_multistream.h" (
            echo === Using STATIC triplet ===
            set VCPKG_DEFAULT_TRIPLET=%STATIC_TRIPLET%
            set VCPKG_TARGET_TRIPLET=%STATIC_TRIPLET%
            set VCPKGRS_DYNAMIC=0
            set BINDGEN_EXTRA_CLANG_ARGS=-I%VCPKG_ROOT%\installed\%STATIC_TRIPLET%\include
          ) else if exist "%VCPKG_ROOT%\installed\%DYNAMIC_TRIPLET%\include\opus\opus_multistream.h" (
            echo === Using DYNAMIC triplet (fallback) ===
            set VCPKG_DEFAULT_TRIPLET=%DYNAMIC_TRIPLET%
            set VCPKG_TARGET_TRIPLET=%DYNAMIC_TRIPLET%
            set VCPKGRS_DYNAMIC=1
            set BINDGEN_EXTRA_CLANG_ARGS=-I%VCPKG_ROOT%\installed\%DYNAMIC_TRIPLET%\include
          ) else (
            echo FATAL: Opus headers not found in either triplet under VCPKG_ROOT=%VCPKG_ROOT%
            dir "%VCPKG_ROOT%\installed"
            exit /b 1
          )

          echo VCPKG_ROOT=%VCPKG_ROOT%
          echo VCPKG_DEFAULT_TRIPLET=%VCPKG_DEFAULT_TRIPLET%
          echo VCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET%
          echo VCPKGRS_DYNAMIC=%VCPKGRS_DYNAMIC%
          echo BINDGEN_EXTRA_CLANG_ARGS=%BINDGEN_EXTRA_CLANG_ARGS%

          rem 4) Сборка клиента
          rustc --version
          cargo --version
          set CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          cargo build --release -v --package rustdesk

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-msvc
          path: rustdesk/target/release/rustdesk.exe
