name: Build RustDesk Client (custom server, vcpkg auto-fallback, MSVC)

on:
  workflow_dispatch:

jobs:
  build-win-msvc:
    runs-on: windows-latest
    env:
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}   # hbbs: host:port (например, hbbs.example.com:21115)
      RS_PUB_KEY:        ${{ vars.RS_PUB_KEY }}          # ssh-ed25519 AAAA... (одной строкой)
      RELAY_SERVER:      ${{ vars.RELAY_SERVER }}        # опционально: hbbr.example.com:21117
      RUST_BACKTRACE: "1"
      CARGO_TERM_COLOR: always
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - name: Checkout this CI repo
        uses: actions/checkout@v4

      # Полная зачистка
      - name: Cleanup previous run
        shell: cmd
        run: |
          if exist rustdesk rmdir /s /q rustdesk
          if exist _vcpkg rmdir /s /q _vcpkg

      # Клонируем КЛИЕНТ rustdesk
      - name: Clone RustDesk (client) + submodules
        shell: cmd
        run: |
          git config --global core.longpaths true
          git clone https://github.com/rustdesk/rustdesk.git rustdesk
          git -C rustdesk submodule sync --recursive
          git -C rustdesk submodule update --init --recursive

      # Rust (MSVC)
      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      # Flutter для GUI
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        shell: pwsh
        run: flutter doctor -v

      # Инструменты C/C++
      - name: Install build tools (cmd)
        shell: cmd
        run: |
          choco install cmake ninja -y --no-progress
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart" -y --no-progress
          cmake --version
          ninja --version

      # vcpkg — ставим В КАТАЛОГ _vcpkg в корне workspace
      - name: Setup vcpkg and install deps (opus static+dynamic, libvpx/libyuv static)
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git _vcpkg
          call _vcpkg\bootstrap-vcpkg.bat
          _vcpkg\vcpkg.exe install opus:x64-windows opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static
          rem Покажем что реально появилось
          dir _vcpkg\installed
          if exist _vcpkg\installed\x64-windows\include\opus       dir _vcpkg\installed\x64-windows\include\opus
          if exist _vcpkg\installed\x64-windows-static\include\opus dir _vcpkg\installed\x64-windows-static\include\opus

      # Проверка наличия заголовков статического opus
      - name: Verify Opus headers (static)
        shell: cmd
        run: |
          if not exist _vcpkg\installed\x64-windows-static\include\opus\opus_multistream.h (
            echo WARNING: static opus headers not found, will fallback to dynamic at build step.
          ) else (
            echo OK: static opus headers present
          )

      # Печать ваших переменных (проверка)
      - name: Print custom vars
        shell: pwsh
        run: |
          echo "RENDEZVOUS_SERVER=$env:RENDEZVOUS_SERVER"
          if ($env:RELAY_SERVER) { echo "RELAY_SERVER=$env:RELAY_SERVER" }
          echo "RS_PUB_KEY length: $($env:RS_PUB_KEY.Length)"

      # Сборка В ОДНОМ cmd-шаге: VsDevCmd + vcpkg + авто-fallBack
      - name: Build RustDesk (release, MSVC) with vcpkg auto-fallback
        shell: cmd
        working-directory: rustdesk
        env:
          RENDEZVOUS_SERVER: ${{ env.RENDEZVOUS_SERVER }}
          RELAY_SERVER:      ${{ env.RELAY_SERVER }}
          RS_PUB_KEY:        ${{ env.RS_PUB_KEY }}
        run: |
          rem 1) Инициализируем MSVC/SDK
          if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          ) else (
            call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=x64
          )

          rem 2) Указываем vcpkg из ПРЕДСКАЗУЕМОГО каталога _vcpkg
          set VCPKG_ROOT=%GITHUB_WORKSPACE%\_vcpkg
          set STATIC_TRIPLET=x64-windows-static
          set DYNAMIC_TRIPLET=x64-windows

          rem 3) Автоматический выбор: если есть static-headers — статическая сборка, иначе — динамическая
          if exist "%VCPKG_ROOT%\installed\%STATIC_TRIPLET%\include\opus\opus_multistream.h" (
            echo === Using STATIC triplet ===
            set VCPKG_DEFAULT_TRIPLET=%STATIC_TRIPLET%
            set VCPKG_TARGET_TRIPLET=%STATIC_TRIPLET%
            set VCPKGRS_DYNAMIC=0
            set BINDGEN_EXTRA_CLANG_ARGS=-I%VCPKG_ROOT%\installed\%STATIC_TRIPLET%\include
          ) else (
            echo === Static headers not found, FALLBACK to DYNAMIC triplet ===
            if not exist "%VCPKG_ROOT%\installed\%DYNAMIC_TRIPLET%\include\opus\opus_multistream.h" (
              echo FATAL: Opus headers not found for dynamic triplet either.
              dir "%VCPKG_ROOT%\installed"
              exit /b 1
            )
            set VCPKG_DEFAULT_TRIPLET=%DYNAMIC_TRIPLET%
            set VCPKG_TARGET_TRIPLET=%DYNAMIC_TRIPLET%
            set VCPKGRS_DYNAMIC=1
            set BINDGEN_EXTRA_CLANG_ARGS=-I%VCPKG_ROOT%\installed\%DYNAMIC_TRIPLET%\include
          )

          echo VCPKG_ROOT=%VCPKG_ROOT%
          echo VCPKG_DEFAULT_TRIPLET=%VCPKG_DEFAULT_TRIPLET%
          echo VCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET%
          echo VCPKGRS_DYNAMIC=%VCPKGRS_DYNAMIC%
          echo BINDGEN_EXTRA_CLANG_ARGS=%BINDGEN_EXTRA_CLANG_ARGS%

          rem 4) Сборка клиента
          rustc --version
          cargo --version
          set CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          cargo build --release -v --package rustdesk

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-msvc
          path: rustdesk/target/release/rustdesk.exe
