name: Build RustDesk Client (custom server, vcpkg static, MSVC)

on:
  workflow_dispatch:

jobs:
  build-win-msvc:
    runs-on: windows-latest
    env:
      # === ваши переменные в Settings → Actions → Variables ===
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}   # напр.: hbbs.example.com:21115
      RS_PUB_KEY:        ${{ vars.RS_PUB_KEY }}          # ssh-ed25519 AAAA... (одной строкой)
      RELAY_SERVER:      ${{ vars.RELAY_SERVER }}        # опц.: hbbr.example.com:21117
      # Диагностика
      RUST_BACKTRACE: "1"
      CARGO_TERM_COLOR: always
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - name: Checkout this CI repo
        uses: actions/checkout@v4

      # Полная зачистка — чтобы не было повторных rustdesk/rustdesk/... и битого vcpkg
      - name: Cleanup previous run
        shell: cmd
        run: |
          if exist rustdesk rmdir /s /q rustdesk
          if exist vcpkg rmdir /s /q vcpkg

      # Клонируем ИМЕННО клиент rustdesk и инициализируем сабмодули из корня
      - name: Clone RustDesk (client) + submodules
        shell: cmd
        run: |
          git config --global core.longpaths true
          git clone https://github.com/rustdesk/rustdesk.git rustdesk
          git -C rustdesk submodule sync --recursive
          git -C rustdesk submodule update --init --recursive

      # Rust (MSVC)
      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      # Flutter (GUI)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        shell: pwsh
        run: flutter doctor -v

      # Инструменты C/C++ через cmd (без refreshenv)
      - name: Install build tools (cmd)
        shell: cmd
        run: |
          choco install cmake ninja -y --no-progress
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart" -y --no-progress
          cmake --version
          ninja --version

      # vcpkg + СТАТИЧЕСКИЕ зависимости
      - name: Setup vcpkg and install static deps
        shell: cmd
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          rem Ставим статические порты, нужные для magnum-opus и scrap:
          .\vcpkg\vcpkg.exe install opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static

      # Sanity-check: проверим, что заголовки Opus реально на месте
      - name: Verify Opus headers exist
        shell: cmd
        run: |
          if not exist vcpkg\installed\x64-windows-static\include\opus\opus_multistream.h (
            echo FATAL: vcpkg opus headers not found in x64-windows-static\include\opus
            dir vcpkg\installed\x64-windows-static\include
            exit /b 1
          ) else (
            echo OK: opus headers present
            dir vcpkg\installed\x64-windows-static\include\opus
          )

      # Печать ваших переменных
      - name: Print custom vars
        shell: pwsh
        run: |
          echo "RENDEZVOUS_SERVER=$env:RENDEZVOUS_SERVER"
          if ($env:RELAY_SERVER) { echo "RELAY_SERVER=$env:RELAY_SERVER" }
          echo "RS_PUB_KEY length: $($env:RS_PUB_KEY.Length)"

      # Сборка: один cmd-шаг — активируем VS среду, задаём vcpkg и include для bindgen/clang, собираем
      - name: Build RustDesk (release, MSVC) in VS DevCmd + vcpkg static env
        shell: cmd
        working-directory: rustdesk
        env:
          RENDEZVOUS_SERVER: ${{ env.RENDEZVOUS_SERVER }}
          RELAY_SERVER:      ${{ env.RELAY_SERVER }}
          RS_PUB_KEY:        ${{ env.RS_PUB_KEY }}
        run: |
          rem 1) MSVC/Windows SDK окружение
          if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          ) else (
            call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=x64
          )

          rem 2) vcpkg (статический триплет)
          set VCPKG_ROOT=%GITHUB_WORKSPACE%\vcpkg
          set VCPKG_DEFAULT_TRIPLET=x64-windows-static
          set VCPKG_TARGET_TRIPLET=x64-windows-static

          rem 3) bindgen/clang должны видеть инклюды vcpkg
          set BINDGEN_EXTRA_CLANG_ARGS=-I%VCPKG_ROOT%\installed\%VCPKG_TARGET_TRIPLET%\include

          echo VCPKG_ROOT=%VCPKG_ROOT%
          echo VCPKG_DEFAULT_TRIPLET=%VCPKG_DEFAULT_TRIPLET%
          echo VCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET%
          echo BINDGEN_EXTRA_CLANG_ARGS=%BINDGEN_EXTRA_CLANG_ARGS%

          rem 4) Сборка клиента
          rustc --version
          cargo --version
          set CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true

          cargo build --release -v --package rustdesk

      - name: Upload artifact (EXE)
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-msvc
          path: rustdesk/target/release/rustdesk.exe
