name: Build RustDesk Client (custom server, MSVC, reliable vcpkg)

on:
  workflow_dispatch:

jobs:
  build-win-msvc:
    runs-on: windows-latest
    env:
      # Заполни в Settings → Secrets and variables → Actions → Variables
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}   # hbbs: host:port
      RS_PUB_KEY:        ${{ vars.RS_PUB_KEY }}          # ssh-ed25519 AAAA... (одной строкой)
      RELAY_SERVER:      ${{ vars.RELAY_SERVER }}        # опционально: hbbr:port
      # Диагностика
      RUST_BACKTRACE: "1"
      CARGO_TERM_COLOR: always
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cleanup previous run
        shell: cmd
        run: |
          if exist rustdesk rmdir /s /q rustdesk

      - name: Clone RustDesk (client) + submodules
        shell: cmd
        run: |
          git config --global core.longpaths true
          git clone https://github.com/rustdesk/rustdesk.git rustdesk
          git -C rustdesk submodule sync --recursive
          git -C rustdesk submodule update --init --recursive

      - name: Setup Rust (MSVC)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter doctor
        shell: pwsh
        run: flutter doctor -v

      - name: Install C/C++ build tools (Chocolatey)
        shell: cmd
        run: |
          choco install cmake ninja -y --no-progress
          choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --quiet --norestart" -y --no-progress
          cmake --version
          ninja --version

      # Bootstrap/cache vcpkg через lukka (manifest mode)
      - name: setup-vcpkg (x64-windows-static)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ''     # можно зафиксировать конкретный commit
          vcpkgDirectory: ${{ runner.temp }}\vcpkg
          vcpkgJsonGlob: rustdesk/vcpkg.json
          triplet: x64-windows-static
          appendedCacheKey: rustdesk-static

      - name: setup-vcpkg (x64-windows)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: ''
          vcpkgDirectory: ${{ runner.temp }}\vcpkg
          vcpkgJsonGlob: rustdesk/vcpkg.json
          triplet: x64-windows
          appendedCacheKey: rustdesk-dynamic

      # Зафиксировать единый VCPKG_ROOT для всех следующих шагов
      - name: Pin VCPKG_ROOT to $RUNNER_TEMP\vcpkg
        shell: pwsh
        run: |
          $root = "$env:RUNNER_TEMP\vcpkg"
          "VCPKG_ROOT=$root" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Pinned VCPKG_ROOT to $root"

      # Classic mode: явная установка необходимых портов под зафиксированный VCPKG_ROOT
      - name: vcpkg classic install (static: opus, libvpx, libyuv)
        shell: cmd
        run: |
          set VCPKG_FEATURE_FLAGS=-manifests
          if not exist "%VCPKG_ROOT%" (
            echo FATAL: VCPKG_ROOT not found: %VCPKG_ROOT%
            exit /b 1
          )
          dir "%VCPKG_ROOT%"
          "%VCPKG_ROOT%\vcpkg.exe" install opus:x64-windows-static libvpx:x64-windows-static libyuv:x64-windows-static
          if exist "%VCPKG_ROOT%\installed\x64-windows-static\include\opus" dir "%VCPKG_ROOT%\installed\x64-windows-static\include\opus"

      - name: vcpkg classic install (dynamic: opus)
        shell: cmd
        run: |
          set VCPKG_FEATURE_FLAGS=-manifests
          "%VCPKG_ROOT%\vcpkg.exe" install opus:x64-windows
          if exist "%VCPKG_ROOT%\installed\x64-windows\include\opus" dir "%VCPKG_ROOT%\installed\x64-windows\include\opus"

      # Найти opus_multistream.h и выбрать триплет/инклюд-путь
      - name: Locate Opus headers and export env
        shell: pwsh
        run: |
          $root = $env:VCPKG_ROOT
          Write-Host "VCPKG_ROOT = $root"
          if (-not (Test-Path "$root/installed")) {
            Write-Host "FATAL: $root/installed not found"
            exit 1
          }
          $hits = Get-ChildItem -Path "$root/installed" -Recurse -Filter 'opus_multistream.h' -ErrorAction SilentlyContinue
          if (-not $hits) {
            Write-Host "FATAL: opus_multistream.h not found under $root/installed"
            Get-ChildItem -Path "$root/installed" -Recurse -ErrorAction SilentlyContinue | Select-Object FullName | Out-Host
            exit 1
          }
          $hit = $hits | Where-Object { $_.FullName -match 'x64-windows-static' } | Select-Object -First 1
          if (-not $hit) { $hit = $hits | Where-Object { $_.FullName -match 'x64-windows' } | Select-Object -First 1 }
          $includeOpus = Split-Path $hit.FullName -Parent
          $includeBase = Split-Path $includeOpus -Parent
          $triplet = Split-Path (Split-Path $includeBase -Parent) -Leaf
          $dyn = if ($triplet -eq 'x64-windows-static') { '0' } else { '1' }

          "CHOSEN_TRIPLET=$triplet"   | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "INCLUDE_BASE=$includeBase" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "VCPKGRS_DYNAMIC=$dyn"      | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

          Write-Host "Chosen triplet: $triplet"
          Write-Host "Include base   : $includeBase"
          Write-Host "VCPKGRS_DYNAMIC: $dyn"

      # Сборка: сохранить/восстановить VCPKG_ROOT вокруг VsDevCmd, использовать найденные значения
      - name: Build RustDesk (release, MSVC)
        shell: cmd
        working-directory: rustdesk
        env:
          RENDEZVOUS_SERVER: ${{ env.RENDEZVOUS_SERVER }}
          RELAY_SERVER:      ${{ env.RELAY_SERVER }}
          RS_PUB_KEY:        ${{ env.RS_PUB_KEY }}
        run: |
          rem 0) Сохраняем VCPKG_ROOT
          set "_VCPKG_ROOT=%VCPKG_ROOT%"

          rem 1) Активируем MSVC/SDK (перезаписывает VCPKG_ROOT)
          if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" (
            call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          ) else (
            call "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\VsDevCmd.bat" -arch=x64
          )

          rem 2) Восстанавливаем VCPKG_ROOT
          set "VCPKG_ROOT=%_VCPKG_ROOT%"
          echo Restored VCPKG_ROOT=%VCPKG_ROOT%

          rem 3) Применяем выбранный триплет/инклюды
          set VCPKG_DEFAULT_TRIPLET=%CHOSEN_TRIPLET%
          set VCPKG_TARGET_TRIPLET=%CHOSEN_TRIPLET%
          set BINDGEN_EXTRA_CLANG_ARGS=-I"%INCLUDE_BASE%"

          echo VCPKG_DEFAULT_TRIPLET=%VCPKG_DEFAULT_TRIPLET%
          echo VCPKG_TARGET_TRIPLET=%VCPKG_TARGET_TRIPLET%
          echo VCPKGRS_DYNAMIC=%VCPKGRS_DYNAMIC%
          echo BINDGEN_EXTRA_CLANG_ARGS=%BINDGEN_EXTRA_CLANG_ARGS%

          rustc --version
          cargo --version
          set CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
          cargo build --release -v --package rustdesk

      # Если динамика — положить DLL рядом с exe
      - name: Bundle runtime DLLs if dynamic
        shell: cmd
        run: |
          if "%VCPKGRS_DYNAMIC%"=="1" (
            echo Copying vcpkg DLLs...
            if not exist dist mkdir dist
            copy "%VCPKG_ROOT%\installed\%VCPKG_TARGET_TRIPLET%\bin\*.dll" dist\ >nul
            copy "rustdesk\target\release\rustdesk.exe" dist\ >nul
          ) else (
            echo Static build detected.
            if not exist dist mkdir dist
            copy "rustdesk\target\release\rustdesk.exe" dist\ >nul
          )

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-msvc-exe
          path: rustdesk/target/release/rustdesk.exe

      - name: Upload portable folder
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-msvc-portable
          path: dist/**
